const express=require('express');
const { isAuth } = require('../Middlewares/isAuth');
const { productFetching, addingProduct, updateProduct, deleteProduct, filteration } = require('../Controllers/products.controllers');
const app=express();
app.get('/allProducts',isAuth,productFetching);
app.post('/addProduct',isAuth,addingProduct);
app.put('/updateProduct',isAuth,updateProduct);
app.delete('/deleteProduct/:id',isAuth,deleteProduct);
app.get('/filter',isAuth,filteration);
module.exports=app;